version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: helloworld.app


libraries:
- name: webapp2
  version: "2.5.2"
- name: PIL
  version: latest
- name: lxml
  version: "2.3"   # or "latest"
- name: ssl
  version: latest


